# Data for books, songs, movies, and travel places
data = {
    "books": {
    "The Great Gatsby": {"author": "F. Scott Fitzgerald", "genre": "Fiction"},
    "To Kill a Mockingbird": {"author": "Harper Lee", "genre": "Fiction"},
    "1984": {"author": "George Orwell", "genre": "Science Fiction"},
    "Pride and Prejudice": {"author": "Jane Austen", "genre": "Romance"},
    "Harry Potter and the Sorcerer's Stone": {"author": "J.K. Rowling", "genre": "Fantasy"},
    "The Catcher in the Rye": {"author": "J.D. Salinger", "genre": "Fiction"},
    "The Lord of the Rings": {"author": "J.R.R. Tolkien", "genre": "Fantasy"},
    "To Kill a Mockingbird": {"author": "Harper Lee", "genre": "Fiction"},
    "Animal Farm": {"author": "George Orwell", "genre": "Fiction"},
    "The Hobbit": {"author": "J.R.R. Tolkien", "genre": "Fantasy"},
    "Brave New World": {"author": "Aldous Huxley", "genre": "Science Fiction"},
    "The Hunger Games": {"author": "Suzanne Collins", "genre": "Science Fiction"},
    "The Diary of a Young Girl": {"author": "Anne Frank", "genre": "Autobiography"},
    "Frankenstein": {"author": "Mary Shelley", "genre": "Gothic Fiction"},
    "Moby-Dick": {"author": "Herman Melville", "genre": "Adventure"},
    "The Picture of Dorian Gray": {"author": "Oscar Wilde", "genre": "Gothic Fiction"},
    "The Hitchhiker's Guide to the Galaxy": {"author": "Douglas Adams", "genre": "Science Fiction"},
    "The Chronicles of Narnia": {"author": "C.S. Lewis", "genre": "Fantasy"},
    "Jane Eyre": {"author": "Charlotte Brontë", "genre": "Gothic Fiction"},
    "One Hundred Years of Solitude": {"author": "Gabriel García Márquez", "genre": "Magic Realism"},
    "The Count of Monte Cristo": {"author": "Alexandre Dumas", "genre": "Adventure"},
    "The Bell Jar": {"author": "Sylvia Plath", "genre": "Autobiography"},
    "The Odyssey": {"author": "Homer", "genre": "Epic Poetry"},
    "The Iliad": {"author": "Homer", "genre": "Epic Poetry"},
    "Anna Karenina": {"author": "Leo Tolstoy", "genre": "Fiction"},
    "Crime and Punishment": {"author": "Fyodor Dostoevsky", "genre": "Fiction"},
    "The Brothers Karamazov": {"author": "Fyodor Dostoevsky", "genre": "Fiction"},
    "Don Quixote": {"author": "Miguel de Cervantes", "genre": "Adventure"},
    "The Canterbury Tales": {"author": "Geoffrey Chaucer", "genre": "Poetry"},
    "Wuthering Heights": {"author": "Emily Brontë", "genre": "Gothic Fiction"},
    "Gone with the Wind": {"author": "Margaret Mitchell", "genre": "Historical Fiction"},
    "Les Misérables": {"author": "Victor Hugo", "genre": "Historical Fiction"},
    "The Alchemist": {"author": "Paulo Coelho", "genre": "Fiction"},
    "Little Women": {"author": "Louisa May Alcott", "genre": "Fiction"},
    "The Adventures of Sherlock Holmes": {"author": "Arthur Conan Doyle", "genre": "Mystery"},
    "The Divine Comedy": {"author": "Dante Alighieri", "genre": "Epic Poetry"},
    "The Grapes of Wrath": {"author": "John Steinbeck", "genre": "Fiction"},
    "A Tale of Two Cities": {"author": "Charles Dickens", "genre": "Historical Fiction"},
    "The Secret Garden": {"author": "Frances Hodgson Burnett", "genre": "Children's Fiction"},
    "The Phantom of the Opera": {"author": "Gaston Leroux", "genre": "Gothic Fiction"},
    "The Road": {"author": "Cormac McCarthy", "genre": "Post-Apocalyptic Fiction"},
    "Dracula": {"author": "Bram Stoker", "genre": "Gothic Fiction"},
    "The Adventures of Tom Sawyer": {"author": "Mark Twain", "genre": "Adventure"},
    "The Importance of Being Earnest": {"author": "Oscar Wilde", "genre": "Comedy"},
    "The Shining": {"author": "Stephen King", "genre": "Horror"},
    "Great Expectations": {"author": "Charles Dickens", "genre": "Fiction"},
    "The Color Purple": {"author": "Alice Walker", "genre": "Fiction"},
    "The Old Man and the Sea": {"author": "Ernest Hemingway", "genre": "Fiction"},
    "The Road Less Traveled": {"author": "M. Scott Peck", "genre": "Self-Help"},
    "The Joy Luck Club": {"author": "Amy Tan", "genre": "Fiction"},
    "The Kite Runner": {"author": "Khaled Hosseini", "genre": "Fiction"},
    "Life of Pi": {"author": "Yann Martel", "genre": "Adventure"},
    "The Girl with the Dragon Tattoo": {"author": "Stieg Larsson", "genre": "Mystery"},
    "The Outsiders": {"author": "S.E. Hinton", "genre": "Young Adult"},
    "The Da Vinci Code": {"author": "Dan Brown", "genre": "Thriller"},
    "The Fault in Our Stars": {"author": "John Green", "genre": "Young Adult"},
    "The Help": {"author": "Kathryn Stockett", "genre": "Historical Fiction"},
    "The Handmaid's Tale": {"author": "Margaret Atwood", "genre": "Science Fiction"},
    "The Martian": {"author": "Andy Weir", "genre": "Science Fiction"},
    "Jurassic Park": {"author": "Michael Crichton", "genre": "Science Fiction"},
    "The Road to Wigan Pier": {"author": "George Orwell", "genre": "Non-Fiction"},
    "Fear and Loathing in Las Vegas": {"author": "Hunter S. Thompson", "genre": "Autobiography"},
    "Lord of the Flies": {"author": "William Golding", "genre": "Fiction"},
    "The Sun Also Rises": {"author": "Ernest Hemingway", "genre": "Fiction"},
    "A Clockwork Orange": {"author": "Anthony Burgess", "genre": "Science Fiction"},
    "The Name of the Wind": {"author": "Patrick Rothfuss", "genre": "Fantasy"},
    "The Pillars of the Earth": {"author": "Ken Follett", "genre": "Historical Fiction"},
    "American Gods": {"author": "Neil Gaiman", "genre": "Fantasy"},
    "The Handmaid's Tale": {"author": "Margaret Atwood", "genre": "Science Fiction"},
    "The Stand": {"author": "Stephen King", "genre": "Post-Apocalyptic Fiction"},
    "Catch-22": {"author": "Joseph Heller", "genre": "Satire"},
    "The Great Alone": {"author": "Kristin Hannah", "genre": "Fiction"},
    "The Goldfinch": {"author": "Donna Tartt", "genre": "Fiction"},
    "The Night Circus": {"author": "Erin Morgenstern", "genre": "Fantasy"},
    "A Game of Thrones": {"author": "George R.R. Martin", "genre": "Fantasy"},
    "The Girl on the Train": {"author": "Paula Hawkins", "genre": "Thriller"},
    "The Road": {"author": "Cormac McCarthy", "genre": "Post-Apocalyptic Fiction"},
    "The Help": {"author": "Kathryn Stockett", "genre": "Historical Fiction"},
    "The Book Thief": {"author": "Markus Zusak", "genre": "Historical Fiction"},
    "All the Light We Cannot See": {"author": "Anthony Doerr", "genre": "Historical Fiction"},
    "The Fault in Our Stars": {"author": "John Green", "genre": "Young Adult"},
    "Me Before You": {"author": "Jojo Moyes", "genre": "Romance"},
    "The Nightingale": {"author": "Kristin Hannah", "genre": "Historical Fiction"},
    "Before We Were Yours": {"author": "Lisa Wingate", "genre": "Historical Fiction"},
    "Educated": {"author": "Tara Westover", "genre": "Autobiography"},
    "Where the Crawdads Sing": {"author": "Delia Owens", "genre": "Mystery"},
    "Becoming": {"author": "Michelle Obama", "genre": "Autobiography"},
    "Circe": {"author": "Madeline Miller", "genre": "Fantasy"},
    "The Silent Patient": {"author": "Alex Michaelides", "genre": "Mystery"},
    "The Tattooist of Auschwitz": {"author": "Heather Morris", "genre": "Historical Fiction"}
    },
    "songs": {
    "Shape of You": {"artist": "Ed Sheeran", "genre": "Pop"},
    "Bohemian Rhapsody": {"artist": "Queen", "genre": "Rock"},
    "Someone Like You": {"artist": "Adele", "genre": "Pop"},
    "Despacito": {"artist": "Luis Fonsi", "genre": "Latin"},
    "Uptown Funk": {"artist": "Mark Ronson ft. Bruno Mars", "genre": "Funk"},
    "Don't Stop Believin'": {"artist": "Journey", "genre": "Rock"},
    "Billie Jean": {"artist": "Michael Jackson", "genre": "Pop"},
    "Sweet Child o' Mine": {"artist": "Guns N' Roses", "genre": "Rock"},
    "Rolling in the Deep": {"artist": "Adele", "genre": "Pop"},
    "Hotel California": {"artist": "Eagles", "genre": "Rock"},
    "Smooth": {"artist": "Santana ft. Rob Thomas", "genre": "Rock"},
    "Hips Don't Lie": {"artist": "Shakira ft. Wyclef Jean", "genre": "Latin"},
    "Smells Like Teen Spirit": {"artist": "Nirvana", "genre": "Rock"},
    "Shape of My Heart": {"artist": "Sting", "genre": "Pop"},
    "Livin' on a Prayer": {"artist": "Bon Jovi", "genre": "Rock"},
    "Girls Just Want to Have Fun": {"artist": "Cyndi Lauper", "genre": "Pop"},
    "Every Breath You Take": {"artist": "The Police", "genre": "Rock"},
    "Hey Jude": {"artist": "The Beatles", "genre": "Rock"},
    "I Will Always Love You": {"artist": "Whitney Houston", "genre": "Pop"},
    "Imagine": {"artist": "John Lennon", "genre": "Pop"},
    "Wonderwall": {"artist": "Oasis", "genre": "Rock"},
    "Like a Rolling Stone": {"artist": "Bob Dylan", "genre": "Rock"},
    "Sweet Caroline": {"artist": "Neil Diamond", "genre": "Pop"},
    "Take On Me": {"artist": "a-ha", "genre": "Pop"},
    "Thriller": {"artist": "Michael Jackson", "genre": "Pop"},
    "Wonderful Tonight": {"artist": "Eric Clapton", "genre": "Rock"},
    "I Want to Hold Your Hand": {"artist": "The Beatles", "genre": "Rock"},
    "Love Shack": {"artist": "The B-52's", "genre": "Pop"},
    "Boogie Wonderland": {"artist": "Earth, Wind & Fire with The Emotions", "genre": "Funk"},
    "My Heart Will Go On": {"artist": "Celine Dion", "genre": "Pop"},
    "Kashmir": {"artist": "Led Zeppelin", "genre": "Rock"},
    "Another Brick in the Wall, Pt. 2": {"artist": "Pink Floyd", "genre": "Rock"},
    "Purple Rain": {"artist": "Prince and The Revolution", "genre": "Pop"},
    "Piano Man": {"artist": "Billy Joel", "genre": "Pop"},
    "Crazy": {"artist": "Gnarls Barkley", "genre": "Pop"},
    "Every Little Thing She Does Is Magic": {"artist": "The Police", "genre": "Rock"},
    "Africa": {"artist": "Toto", "genre": "Rock"},
    "Eye of the Tiger": {"artist": "Survivor", "genre": "Rock"},
    "Under Pressure": {"artist": "Queen & David Bowie", "genre": "Rock"},
    "Careless Whisper": {"artist": "George Michael", "genre": "Pop"},
    "Brown Eyed Girl": {"artist": "Van Morrison", "genre": "Pop"},
    "I Want to Know What Love Is": {"artist": "Foreigner", "genre": "Rock"},
    "Don't You (Forget About Me)": {"artist": "Simple Minds", "genre": "Pop"},
    "Here Comes the Sun": {"artist": "The Beatles", "genre": "Pop"},
    "I Wanna Dance with Somebody (Who Loves Me)": {"artist": "Whitney Houston", "genre": "Pop"},
    "Dancing Queen": {"artist": "ABBA", "genre": "Pop"},
    "Bohemian Like You": {"artist": "The Dandy Warhols", "genre": "Rock"},
    "Drops of Jupiter (Tell Me)": {"artist": "Train", "genre": "Rock"},
    "Total Eclipse of the Heart": {"artist": "Bonnie Tyler", "genre": "Pop"},
    "I Will Survive": {"artist": "Gloria Gaynor", "genre": "Disco"},
    "The Sound of Silence": {"artist": "Simon & Garfunkel", "genre": "Folk"},
    "Take Me Home, Country Roads": {"artist": "John Denver", "genre": "Country"},
    "Let It Be": {"artist": "The Beatles", "genre": "Pop"},
    "American Pie": {"artist": "Don McLean", "genre": "Pop"},
    "Wannabe": {"artist": "Spice Girls", "genre": "Pop"},
    "My Way": {"artist": "Frank Sinatra", "genre": "Jazz"},
    "Black Dog": {"artist": "Led Zeppelin", "genre": "Rock"},
    "Dream On": {"artist": "Aerosmith", "genre": "Rock"},
    "Don't Speak": {"artist": "No Doubt", "genre": "Pop"},
    "Bennie and the Jets": {"artist": "Elton John", "genre": "Pop"},
    "Hotel California (Acoustic Version)": {"artist": "Eagles", "genre": "Rock"},
    "Lose Yourself": {"artist": "Eminem", "genre": "Hip Hop"},
    "Blue Suede Shoes": {"artist": "Elvis Presley", "genre": "Rock"},
    "Stairway to Heaven": {"artist": "Led Zeppelin", "genre": "Rock"},
    "I'm Yours": {"artist": "Jason Mraz", "genre": "Pop"},
    "The Scientist": {"artist": "Coldplay", "genre": "Pop"},
    "Brown Sugar": {"artist": "The Rolling Stones", "genre": "Rock"},
    "Let's Get It On": {"artist": "Marvin Gaye", "genre": "R&B"},
    "Sultans of Swing": {"artist": "Dire Straits", "genre": "Rock"},
    "Here, There and Everywhere": {"artist": "The Beatles", "genre": "Pop"},
    "I Still Haven't Found What I'm Looking For": {"artist": "U2", "genre": "Rock"},
    "La Bamba": {"artist": "Ritchie Valens", "genre": "Latin"},
    "Come Together": {"artist": "The Beatles", "genre": "Rock"},
    "Dancing in the Street": {"artist": "Martha and the Vandellas", "genre": "Pop"},
    "Born to Run": {"artist": "Bruce Springsteen", "genre": "Rock"},
    "Good Vibrations": {"artist": "The Beach Boys", "genre": "Pop"},
    "ABC": {"artist": "The Jackson 5", "genre": "Pop"},
    "Satisfaction": {"artist": "The Rolling Stones", "genre": "Rock"},
    "Mrs. Robinson": {"artist": "Simon & Garfunkel", "genre": "Folk"},
    "Let's Dance": {"artist": "David Bowie", "genre": "Pop"},
    "Johnny B. Goode": {"artist": "Chuck Berry", "genre": "Rock"},
    "I'll Be There": {"artist": "The Jackson 5", "genre": "Pop"},
    "Summer of '69": {"artist": "Bryan Adams", "genre": "Rock"},
    "Free Fallin'": {"artist": "Tom Petty", "genre": "Rock"},
    "Walk This Way": {"artist": "Aerosmith", "genre": "Rock"},
    "The Twist": {"artist": "Chubby Checker", "genre": "Pop"},
    "Hey Ya!": {"artist": "OutKast", "genre": "Hip Hop"},
    "Suspicious Minds": {"artist": "Elvis Presley", "genre": "Pop"},
    "Bad Moon Rising": {"artist": "Creedence Clearwater Revival", "genre": "Rock"},
    "Superstition": {"artist": "Stevie Wonder", "genre": "Funk"},
    "Unchained Melody": {"artist": "The Righteous Brothers", "genre": "Pop"},
    "All Along the Watchtower": {"artist": "Jimi Hendrix", "genre": "Rock"},
    "Hey, Soul Sister": {"artist": "Train", "genre": "Pop"},
    "Rock Lobster": {"artist": "The B-52's", "genre": "Pop"},
    "Sweet Home Alabama": {"artist": "Lynyrd Skynyrd", "genre": "Rock"},
    "Bitter Sweet Symphony": {"artist": "The Verve", "genre": "Rock"},
    "I Want You Back": {"artist": "The Jackson 5", "genre": "Pop"},
    "Bridge Over Troubled Water": {"artist": "Simon & Garfunkel", "genre": "Folk"},
    "My Girl": {"artist": "The Temptations", "genre": "R&B"},
    "ABC 123": {"artist": "Jackson 5", "genre": "Pop"},
    "Help!": {"artist": "The Beatles", "genre": "Pop"},
    "Three Little Birds": {"artist": "Bob Marley & The Wailers", "genre": "Reggae"},
    "Twist and Shout": {"artist": "The Beatles", "genre": "Pop"},
    "California Dreamin'": {"artist": "The Mamas & The Papas", "genre": "Pop"},
    "Brown-Eyed Handsome Man": {"artist": "Chuck Berry", "genre": "Rock"},
    "Mrs. Brown, You've Got a Lovely Daughter": {"artist": "Herman's Hermits", "genre": "Pop"},
    "Lean on Me": {"artist": "Bill Withers", "genre": "R&B"},
    "Mrs. Robinson (Simon & Garfunkel)": {"artist": "The Lemonheads", "genre": "Alternative"},
    "Satisfaction (Rolling Stones)": {"artist": "Britney Spears", "genre": "Pop"},
    "All Along the Watchtower (Jimi Hendrix)": {"artist": "Devlin", "genre": "Hip Hop"},
    "Hey Ya! (OutKast)": {"artist": "The Blanks", "genre": "Pop"},
    "Don't Let Me Be Misunderstood": {"artist": "The Animals", "genre": "Rock"},
    "Turn! Turn! Turn! (To Everything There Is a Season)": {"artist": "The Byrds", "genre": "Folk"},
    "That's All Right": {"artist": "Elvis Presley", "genre": "Rock"},
    "I Fought the Law": {"artist": "The Bobby Fuller Four", "genre": "Rock"},
    "You've Got a Friend": {"artist": "James Taylor", "genre": "Folk"},
    "The Lion Sleeps Tonight": {"artist": "The Tokens", "genre": "Pop"},
    "I Heard It Through the Grapevine": {"artist": "Marvin Gaye", "genre": "R&B"},
    "Good Lovin'": {"artist": "The Young Rascals", "genre": "Rock"},
    "California Girls": {"artist": "The Beach Boys", "genre": "Pop"},
    "The Tracks of My Tears": {"artist": "Smokey Robinson & The Miracles", "genre": "R&B"},
    "You Really Got Me": {"artist": "The Kinks", "genre": "Rock"},
    "Everyday People": {"artist": "Sly & The Family Stone", "genre": "Funk"},
    "I Can't Help Myself (Sugar Pie Honey Bunch)": {"artist": "The Four Tops", "genre": "R&B"},
    "Sitting on the Dock of the Bay": {"artist": "Otis Redding", "genre": "R&B"},
    "Hey Joe": {"artist": "Jimi Hendrix", "genre": "Rock"},
    "Sunshine of Your Love": {"artist": "Cream", "genre": "Rock"},
    "She Loves You": {"artist": "The Beatles", "genre": "Pop"},
    "White Room": {"artist": "Cream", "genre": "Rock"},
    "The End": {"artist": "The Doors", "genre": "Rock"},
    "For What It's Worth": {"artist": "Buffalo Springfield", "genre": "Rock"},
    "My Generation": {"artist": "The Who", "genre": "Rock"},
    "The Boxer": {"artist": "Simon & Garfunkel", "genre": "Folk"},
    "Cecilia": {"artist": "Simon & Garfunkel", "genre": "Folk"},
    "I'm a Believer": {"artist": "The Monkees", "genre": "Pop"},
    "King of the Road": {"artist": "Roger Miller", "genre": "Country"},
    "Do Wah Diddy Diddy": {"artist": "Manfred Mann", "genre": "Pop"},
    "Oh, Pretty Woman": {"artist": "Roy Orbison", "genre": "Rock"},
    "Oh! Darling": {"artist": "The Beatles", "genre": "Rock"},
    "Great Balls of Fire": {"artist": "Jerry Lee Lewis", "genre": "Rock"},
    "Proud Mary": {"artist": "Creedence Clearwater Revival", "genre": "Rock"},
    "Riders on the Storm": {"artist": "The Doors", "genre": "Rock"},
    "Roxanne": {"artist": "The Police", "genre": "Rock"},
    "More Than a Feeling": {"artist": "Boston", "genre": "Rock"},
    "We Will Rock You": {"artist": "Queen", "genre": "Rock"},
    "House of the Rising Sun": {"artist": "The Animals", "genre": "Rock"},
    "Dance to the Music": {"artist": "Sly & The Family Stone", "genre": "Funk"},
    "Daydream Believer": {"artist": "The Monkees", "genre": "Pop"},
    "A Day in the Life": {"artist": "The Beatles", "genre": "Rock"},
    "Monday, Monday": {"artist": "The Mamas & The Papas", "genre": "Pop"},
    "Do You Believe in Magic?": {"artist": "The Lovin' Spoonful", "genre": "Pop"},
    "You Keep Me Hangin' On": {"artist": "The Supremes", "genre": "R&B"},
    "I Feel Good": {"artist": "James Brown", "genre": "Funk"},
    "Good Golly, Miss Molly": {"artist": "Little Richard", "genre": "Rock"},
    "I Can See for Miles": {"artist": "The Who", "genre": "Rock"},
    "Bad to the Bone": {"artist": "George Thorogood & The Destroyers", "genre": "Rock"},
    "Where Did Our Love Go": {"artist": "The Supremes", "genre": "R&B"},
    "I'm Walkin'": {"artist": "Fats Domino", "genre": "Rock"},
    "The Wanderer": {"artist": "Dion", "genre": "Rock"},
    "Great Balls of Fire (Jerry Lee Lewis)": {"artist": "Hoodoo Gurus", "genre": "Rock"},
    "My Boyfriend's Back": {"artist": "The Angels", "genre": "Pop"},
    "Sloop John B": {"artist": "The Beach Boys", "genre": "Pop"},
    "Good Vibrations (The Beach Boys)": {"artist": "Todd Rundgren", "genre": "Rock"},
    "I Second That Emotion": {"artist": "Smokey Robinson & The Miracles", "genre": "R&B"},
    "Hey There Delilah": {"artist": "Plain White T's", "genre": "Pop"},
    "Louie Louie": {"artist": "The Kingsmen", "genre": "Rock"},
    "Heartbreak Hotel": {"artist": "Elvis Presley", "genre": "Rock"},
    "People Are Strange": {"artist": "The Doors", "genre": "Rock"},
    "Dance Hall Days": {"artist": "Wang Chung", "genre": "New Wave"},
    "Under the Boardwalk": {"artist": "The Drifters", "genre": "R&B"},
    "Tutti Frutti": {"artist": "Little Richard", "genre": "Rock"},
    "Rock and Roll Music": {"artist": "Chuck Berry", "genre": "Rock"},
    "Jumpin' Jack Flash": {"artist": "The Rolling Stones", "genre": "Rock"},
    "Fortunate Son": {"artist": "Creedence Clearwater Revival", "genre": "Rock"},
    "In the Midnight Hour": {"artist": "Wilson Pickett", "genre": "R&B"},
    "Twistin' the Night Away": {"artist": "Sam Cooke", "genre": "R&B"},
    "A Hard Day's Night": {"artist": "The Beatles", "genre": "Pop"},
    "Rock Around the Clock": {"artist": "Bill Haley & His Comets", "genre": "Rock"},
    "Blueberry Hill": {"artist": "Fats Domino", "genre": "Rock"},
    "I'm a Man": {"artist": "Bo Diddley", "genre": "Rock"},
    "Stand by Me": {"artist": "Ben E. King", "genre": "R&B"},
    "Runaway": {"artist": "Del Shannon", "genre": "Pop"},
    "You've Lost That Lovin' Feelin'": {"artist": "The Righteous Brothers", "genre": "Pop"},
    "She's Not There": {"artist": "The Zombies", "genre": "Rock"},
    "In My Life": {"artist": "The Beatles", "genre": "Pop"},
    "That'll Be the Day": {"artist": "Buddy Holly", "genre": "Rock"},
    "Surfin' U.S.A.": {"artist": "The Beach Boys", "genre": "Pop"},
    "Who'll Stop the Rain": {"artist": "Creedence Clearwater Revival", "genre": "Rock"},
    "Brown Sugar (The Rolling Stones)": {"artist": "Lucky Dube", "genre": "Reggae"},
    "Kicks": {"artist": "Paul Revere & The Raiders", "genre": "Rock"},
    "Please, Please, Please": {"artist": "James Brown & The Famous Flames", "genre": "R&B"},
    "Goodbye Yellow Brick Road": {"artist": "Elton John", "genre": "Pop"},
    "Born in the U.S.A.": {"artist": "Bruce Springsteen", "genre": "Rock"},
    "Gimme Some Lovin'": {"artist": "The Spencer Davis Group", "genre": "Rock"},
    "It's Now or Never": {"artist": "Elvis Presley", "genre": "Pop"},
    "You Really Got Me (The Kinks)": {"artist": "Robert Palmer", "genre": "Rock"},
    "I'm Sorry": {"artist": "Brenda Lee", "genre": "Pop"},
    "White Rabbit": {"artist": "Jefferson Airplane", "genre": "Rock"},
    "Light My Fire": {"artist": "The Doors", "genre": "Rock"},
    "All Shook Up": {"artist": "Elvis Presley", "genre": "Rock"},
    "Travelin' Man": {"artist": "Ricky Nelson", "genre": "Pop"},
    "Oh, Pretty Woman (Roy Orbison)": {"artist": "Gary Moore", "genre": "Rock"},
    "Higher Love": {"artist": "Steve Winwood", "genre": "Pop"},
    "Surfin' Safari": {"artist": "The Beach Boys", "genre": "Pop"},
    "Go Your Own Way": {"artist": "Fleetwood Mac", "genre": "Rock"},
    "The Weight": {"artist": "The Band", "genre": "Rock"},
    "Come As You Are": {"artist": "Nirvana", "genre": "Rock"},
    "Unchain My Heart": {"artist": "Ray Charles", "genre": "R&B"},
    "Dancing in the Dark": {"artist": "Bruce Springsteen", "genre": "Rock"},
    "Brown Eyed Girl (Van Morrison)": {"artist": "Everclear", "genre": "Rock"},
    "Be My Baby": {"artist": "The Ronettes", "genre": "Pop"},
    "Blue Monday": {"artist": "New Order", "genre": "New Wave"},
    "Will You Love Me Tomorrow": {"artist": "The Shirelles", "genre": "Pop"},
    "In the Ghetto": {"artist": "Elvis Presley", "genre": "Pop"},
    "You Can't Hurry Love": {"artist": "The Supremes", "genre": "R&B"},
    "The Night They Drove Old Dixie Down": {"artist": "The Band", "genre": "Rock"},
    "Another One Bites the Dust": {"artist": "Queen", "genre": "Rock"},
    "Then He Kissed Me": {"artist": "The Crystals", "genre": "Pop"},
    "Born on the Bayou": {"artist": "Creedence Clearwater Revival", "genre": "Rock"},
    "Love Me Tender": {"artist": "Elvis Presley", "genre": "Pop"},
    "The Letter": {"artist": "The Box Tops", "genre": "Rock"},
    "I'm a Loser": {"artist": "The Beatles", "genre": "Pop"},
    "Dancing Queen (ABBA)": {"artist": "Sixpence None the Richer", "genre": "Pop"},
    "I Want to Know What Love Is (Foreigner)": {"artist": "Wynonna Judd", "genre": "Country"},
    "Every Breath You Take (The Police)": {"artist": "Puff Daddy ft. Faith Evans & 112", "genre": "Hip Hop"},
    "Let's Dance (David Bowie)": {"artist": "Five", "genre": "Pop"},
    "Don't Stop Believin' (Journey)": {"artist": "Ollie & Jerry", "genre": "Hip Hop"},
    "Imagine (John Lennon)": {"artist": "Eva Cassidy", "genre": "Folk"},
    "With or Without You": {"artist": "U2", "genre": "Rock"},
    "Love Me Do": {"artist": "The Beatles", "genre": "Pop"},
    "You've Got to Hide Your Love Away": {"artist": "The Beatles", "genre": "Rock"},
    "Heart of Gold": {"artist": "Neil Young", "genre": "Folk"},
    "I Will Follow": {"artist": "U2", "genre": "Rock"},
    "Wild World": {"artist": "Cat Stevens", "genre": "Folk"},
    "Knockin' on Heaven's Door": {"artist": "Bob Dylan", "genre": "Rock"},
    "Sweet Baby James": {"artist": "James Taylor", "genre": "Folk"},
    "Take It Easy": {"artist": "Eagles", "genre": "Rock"},
    "Fire and Rain": {"artist": "James Taylor", "genre": "Folk"},
    "American Woman": {"artist": "The Guess Who", "genre": "Rock"},
    "Ain't No Sunshine": {"artist": "Bill Withers", "genre": "R&B"},
    "Space Oddity": {"artist": "David Bowie", "genre": "Rock"},
    "Changes": {"artist": "David Bowie", "genre": "Rock"},
    "Bohemian Rhapsody (Queen)": {"artist": "Panic! At The Disco", "genre": "Pop"},
    "Billie Jean (Michael Jackson)": {"artist": "Chris Cornell", "genre": "Rock"},
    "Uptown Funk (Mark Ronson ft. Bruno Mars)": {"artist": "Kidz Bop Kids", "genre": "Children's Music"},
    "Livin' on a Prayer (Bon Jovi)": {"artist": "Heaven 17", "genre": "Synth-pop"},
    "Smooth (Santana ft. Rob Thomas)": {"artist": "Santana", "genre": "Rock"},
    "Hey Jude (The Beatles)": {"artist": "The Temptations", "genre": "R&B"},
    "Shape of My Heart (Sting)": {"artist": "Backstreet Boys", "genre": "Pop"},
    "Rolling in the Deep (Adele)": {"artist": "Aretha Franklin", "genre": "R&B"},
    "Girls Just Want to Have Fun (Cyndi Lauper)": {"artist": "Miley Cyrus", "genre": "Pop"},
    "Every Breath You Take (The Police)": {"artist": "P. Diddy ft. Nicole Scherzinger", "genre": "Hip Hop"},
    "Someone Like You (Adele)": {"artist": "Kelly Clarkson", "genre": "Pop"},
    "Despacito (Luis Fonsi)": {"artist": "Louis Armstrong", "genre": "Jazz"},
    "Bohemian Rhapsody (Queen)": {"artist": "Elton John", "genre": "Pop"},
    "Shape of You (Ed Sheeran)": {"artist": "Queen", "genre": "Rock"},
    "Don't Stop Believin' (Journey)": {"artist": "Michael Jackson", "genre": "Pop"},
    "Billie Jean (Michael Jackson)": {"artist": "Led Zeppelin", "genre": "Rock"},
    "Uptown Funk (Mark Ronson ft. Bruno Mars)": {"artist": "Adele", "genre": "Pop"},
    "Livin' on a Prayer (Bon Jovi)": {"artist": "Bob Marley & The Wailers", "genre": "Reggae"},
    "Smooth (Santana ft. Rob Thomas)": {"artist": "Beyoncé", "genre": "R&B"},
    "Hey Jude (The Beatles)": {"artist": "Madonna", "genre": "Pop"},
    "Shape of My Heart (Sting)": {"artist": "The Rolling Stones", "genre": "Rock"},
    "Rolling in the Deep (Adele)": {"artist": "Elvis Presley", "genre": "Rock"},
    "Girls Just Want to Have Fun (Cyndi Lauper)": {"artist": "Michael Jackson", "genre": "Pop"},
    "Every Breath You Take (The Police)": {"artist": "Prince", "genre": "Pop"},
    "Someone Like You (Adele)": {"artist": "David Bowie", "genre": "Rock"},
    "Despacito (Luis Fonsi)": {"artist": "Taylor Swift", "genre": "Pop"}
    },
    "movies": {
    "The Shawshank Redemption": {"genre": "Drama", "director": "Frank Darabont"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "Inception": {"genre": "Science Fiction", "director": "Christopher Nolan"},
    "The Matrix": {"genre": "Action", "director": "The Wachowskis"},
    "Forrest Gump": {"genre": "Drama", "director": "Robert Zemeckis"},
    "Pulp Fiction": {"genre": "Crime", "director": "Quentin Tarantino"},
    "The Dark Knight": {"genre": "Action", "director": "Christopher Nolan"},
    "Schindler's List": {"genre": "Biography", "director": "Steven Spielberg"},
    "Fight Club": {"genre": "Drama", "director": "David Fincher"},
    "The Lord of the Rings: The Return of the King": {"genre": "Fantasy", "director": "Peter Jackson"},
    "Goodfellas": {"genre": "Crime", "director": "Martin Scorsese"},
    "The Silence of the Lambs": {"genre": "Thriller", "director": "Jonathan Demme"},
    "The Departed": {"genre": "Crime", "director": "Martin Scorsese"},
    "Saving Private Ryan": {"genre": "War", "director": "Steven Spielberg"},
    "Gladiator": {"genre": "Action", "director": "Ridley Scott"},
    "The Lion King": {"genre": "Animation", "director": "Roger Allers, Rob Minkoff"},
    "The Green Mile": {"genre": "Drama", "director": "Frank Darabont"},
    "The Prestige": {"genre": "Mystery", "director": "Christopher Nolan"},
    "The Godfather Part II": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Usual Suspects": {"genre": "Crime", "director": "Bryan Singer"},
    "Se7en": {"genre": "Crime", "director": "David Fincher"},
    "Leon: The Professional": {"genre": "Action", "director": "Luc Besson"},
    "Interstellar": {"genre": "Science Fiction", "director": "Christopher Nolan"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Shining": {"genre": "Horror", "director": "Stanley Kubrick"},
    "American History X": {"genre": "Drama", "director": "Tony Kaye"},
    "The Pianist": {"genre": "Biography", "director": "Roman Polanski"},
    "American Beauty": {"genre": "Drama", "director": "Sam Mendes"},
    "The Sixth Sense": {"genre": "Thriller", "director": "M. Night Shyamalan"},
    "The Lord of the Rings: The Two Towers": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Truman Show": {"genre": "Comedy", "director": "Peter Weir"},
    "Jurassic Park": {"genre": "Adventure", "director": "Steven Spielberg"},
    "The Godfather Part III": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Departed": {"genre": "Crime", "director": "Martin Scorsese"},
    "The Intouchables": {"genre": "Biography", "director": "Olivier Nakache, Éric Toledano"},
    "The Terminator": {"genre": "Action", "director": "James Cameron"},
    "The Pursuit of Happyness": {"genre": "Biography", "director": "Gabriele Muccino"},
    "The Grand Budapest Hotel": {"genre": "Comedy", "director": "Wes Anderson"},
    "Inglourious Basterds": {"genre": "Adventure", "director": "Quentin Tarantino"},
    "The Professional": {"genre": "Action", "director": "Luc Besson"},
    "Schindler's List": {"genre": "Biography", "director": "Steven Spielberg"},
    "Whiplash": {"genre": "Drama", "director": "Damien Chazelle"},
    "A Beautiful Mind": {"genre": "Biography", "director": "Ron Howard"},
    "The Notebook": {"genre": "Romance", "director": "Nick Cassavetes"},
    "The Avengers": {"genre": "Action", "director": "Joss Whedon"},
    "The Social Network": {"genre": "Biography", "director": "David Fincher"},
    "Casablanca": {"genre": "Romance", "director": "Michael Curtiz"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "Avengers: Infinity War": {"genre": "Action", "director": "Anthony Russo, Joe Russo"},
    "The Pursuit of Happyness": {"genre": "Biography", "director": "Gabriele Muccino"},
    "The Silence of the Lambs": {"genre": "Thriller", "director": "Jonathan Demme"},
    "The Help": {"genre": "Drama", "director": "Tate Taylor"},
    "The Lion King": {"genre": "Animation", "director": "Roger Allers, Rob Minkoff"},
    "The Dark Knight Rises": {"genre": "Action", "director": "Christopher Nolan"},
    "The Great Gatsby": {"genre": "Drama", "director": "Baz Luhrmann"},
    "Schindler's List": {"genre": "Biography", "director": "Steven Spielberg"},
    "The Godfather Part II": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Godfather Part III": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Sixth Sense": {"genre": "Thriller", "director": "M. Night Shyamalan"},
    "The Matrix Reloaded": {"genre": "Action", "director": "The Wachowskis"},
    "The Matrix Revolutions": {"genre": "Action", "director": "The Wachowskis"},
    "The Lion King": {"genre": "Animation", "director": "Roger Allers, Rob Minkoff"},
    "The Green Mile": {"genre": "Drama", "director": "Frank Darabont"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Two Towers": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Return of the King": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Hobbit: An Unexpected Journey": {"genre": "Adventure", "director": "Peter Jackson"},
    "The Hobbit: The Desolation of Smaug": {"genre": "Adventure", "director": "Peter Jackson"},
    "The Hobbit: The Battle of the Five Armies": {"genre": "Adventure", "director": "Peter Jackson"},
    "Forrest Gump": {"genre": "Drama", "director": "Robert Zemeckis"},
    "Inception": {"genre": "Science Fiction", "director": "Christopher Nolan"},
    "The Dark Knight": {"genre": "Action", "director": "Christopher Nolan"},
    "The Shawshank Redemption": {"genre": "Drama", "director": "Frank Darabont"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Dark Knight Rises": {"genre": "Action", "director": "Christopher Nolan"},
    "The Lord of the Rings: The Two Towers": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Return of the King": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Dark Knight": {"genre": "Action", "director": "Christopher Nolan"},
    "The Shawshank Redemption": {"genre": "Drama", "director": "Frank Darabont"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Dark Knight Rises": {"genre": "Action", "director": "Christopher Nolan"},
    "The Lord of the Rings: The Two Towers": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Return of the King": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Dark Knight": {"genre": "Action", "director": "Christopher Nolan"},
    "The Shawshank Redemption": {"genre": "Drama", "director": "Frank Darabont"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Dark Knight Rises": {"genre": "Action", "director": "Christopher Nolan"},
    "The Lord of the Rings: The Two Towers": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Return of the King": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Dark Knight": {"genre": "Action", "director": "Christopher Nolan"},
    "The Shawshank Redemption": {"genre": "Drama", "director": "Frank Darabont"},
    "The Godfather": {"genre": "Crime", "director": "Francis Ford Coppola"},
    "The Lord of the Rings: The Fellowship of the Ring": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Dark Knight Rises": {"genre": "Action", "director": "Christopher Nolan"},
    "The Lord of the Rings: The Two Towers": {"genre": "Fantasy", "director": "Peter Jackson"},
    "The Lord of the Rings: The Return of the King": {"genre": "Fantasy", "director": "Peter Jackson"}
    },
    "travel_places": {
    "Sydney, Australia": {"type": "City"},
    "Bora Bora, French Polynesia": {"type": "Beach"},
    "New York City, USA": {"type": "Metropolis"},
    "Bali, Indonesia": {"type": "Island"},
    "Yellowstone National Park, USA": {"type": "National Park"},
    "London, England": {"type": "City"},
    "Maldives": {"type": "Beach"},
    "Hong Kong": {"type": "Metropolis"},
    "Phuket, Thailand": {"type": "Island"},
    "Yosemite National Park, USA": {"type": "National Park"},
    "Rome, Italy": {"type": "City"},
    "Rio de Janeiro, Brazil": {"type": "Beach"},
    "Los Angeles, USA": {"type": "Metropolis"},
    "Hawaii, USA": {"type": "Island"},
    "Grand Canyon National Park, USA": {"type": "National Park"},
    "Dubai, UAE": {"type": "City"},
    "Cancun, Mexico": {"type": "Beach"},
    "Singapore": {"type": "Metropolis"},
    "Fiji": {"type": "Island"},
    "Rocky Mountain National Park, USA": {"type": "National Park"},
    "Florence, Italy": {"type": "City"},
    "Miami, USA": {"type": "Beach"},
    "Shanghai, China": {"type": "Metropolis"},
    "Seychelles": {"type": "Island"},
    "Zion National Park, USA": {"type": "National Park"},
    "Barcelona, Spain": {"type": "City"},
    "Maui, USA": {"type": "Beach"},
    "Seoul, South Korea": {"type": "Metropolis"},
    "Crete, Greece": {"type": "Island"},
    "Glacier National Park, USA": {"type": "National Park"},
    "Amsterdam, Netherlands": {"type": "City"},
    "Cabo San Lucas, Mexico": {"type": "Beach"},
    "Moscow, Russia": {"type": "Metropolis"},
    "Santorini, Greece": {"type": "Island"},
    "Denali National Park, USA": {"type": "National Park"},
    "Prague, Czech Republic": {"type": "City"},
    "Mykonos, Greece": {"type": "Beach"},
    "Toronto, Canada": {"type": "Metropolis"},
    "Ibiza, Spain": {"type": "Island"},
    "Great Smoky Mountains National Park, USA": {"type": "National Park"},
    "Venice, Italy": {"type": "City"},
    "Cape Town, South Africa": {"type": "Beach"},
    "Las Vegas, USA": {"type": "Metropolis"},
    "Mauritius": {"type": "Island"},
    "Kruger National Park, South Africa": {"type": "National Park"},
    "Edinburgh, Scotland": {"type": "City"},
    "Nice, France": {"type": "Beach"},
    "Chicago, USA": {"type": "Metropolis"},
    "Skiathos, Greece": {"type": "Island"},
    "Banff National Park, Canada": {"type": "National Park"},
    "Vienna, Austria": {"type": "City"},
    "Gold Coast, Australia": {"type": "Beach"},
    "San Francisco, USA": {"type": "Metropolis"},
    "Palawan, Philippines": {"type": "Island"},
    "Grand Teton National Park, USA": {"type": "National Park"},
    "Berlin, Germany": {"type": "City"},
    "Cancun, Mexico": {"type": "Beach"},
    "Bangkok, Thailand": {"type": "Metropolis"},
    "Santorini, Greece": {"type": "Island"},
    "Yellowstone National Park, USA": {"type": "National Park"},
    "Florence, Italy": {"type": "City"},
    "Maui, USA": {"type": "Beach"},
    "Seoul, South Korea": {"type": "Metropolis"},
    "Crete, Greece": {"type": "Island"},
    "Glacier National Park, USA": {"type": "National Park"},
    "Amsterdam, Netherlands": {"type": "City"},
    "Cabo San Lucas, Mexico": {"type": "Beach"},
    "Moscow, Russia": {"type": "Metropolis"},
    "Santorini, Greece": {"type": "Island"},
    "Denali National Park, USA": {"type": "National Park"},
    "Prague, Czech Republic": {"type": "City"},
    "Mykonos, Greece": {"type": "Beach"},
    "Toronto, Canada": {"type": "Metropolis"},
    "Ibiza, Spain": {"type": "Island"},
    "Great Smoky Mountains National Park, USA": {"type": "National Park"},
    "Venice, Italy": {"type": "City"},
    "Cape Town, South Africa": {"type": "Beach"},
    "Las Vegas, USA": {"type": "Metropolis"},
    "Mauritius": {"type": "Island"},
    "Kruger National Park, South Africa": {"type": "National Park"},
    "Edinburgh, Scotland": {"type": "City"},
    "Nice, France": {"type": "Beach"},
    "Chicago, USA": {"type": "Metropolis"},
    "Skiathos, Greece": {"type": "Island"},
    "Banff National Park, Canada": {"type": "National Park"},
    "Vienna, Austria": {"type": "City"},
    "Gold Coast, Australia": {"type": "Beach"},
    "San Francisco, USA": {"type": "Metropolis"},
    "Palawan, Philippines": {"type": "Island"},
    "Grand Teton National Park, USA": {"type": "National Park"},
    "Berlin, Germany": {"type": "City"},
    "Cape Cod, USA": {"type": "Beach"},
    "New Orleans, USA": {"type": "Metropolis"},
    "Bora Bora, French Polynesia": {"type": "Island"},
    "Rocky Mountain National Park, USA": {"type": "National Park"},
    "Barcelona, Spain": {"type": "City"},
    "Tulum, Mexico": {"type": "Beach"},
    "Dublin, Ireland": {"type": "Metropolis"},
    "Maldives": {"type": "Island"},
    "Everglades National Park, USA": {"type": "National Park"},
    "Copenhagen, Denmark": {"type": "City"},
    "Amalfi Coast, Italy": {"type": "Beach"},
    "Washington D.C., USA": {"type": "Metropolis"},
    "Bora Bora, French Polynesia": {"type": "Island"},
    "Arches National Park, USA": {"type": "National Park"},
    "Budapest, Hungary": {"type": "City"},
    "Mauritius": {"type": "Beach"},
    "Dublin, Ireland": {"type": "Metropolis"},
    "Bora Bora, French Polynesia": {"type": "Island"},
    "Yosemite National Park, USA": {"type": "National Park"},
    "Sydney, Australia": {"type": "City"},
    "Bora Bora, French Polynesia": {"type": "Beach"},
    "New York City, USA": {"type": "Metropolis"},
    "Bali, Indonesia": {"type": "Island"},
    "Yellowstone National Park, USA": {"type": "National Park"},
    "London, England": {"type": "City"},
    "Maldives": {"type": "Beach"},
    "Hong Kong": {"type": "Metropolis"},
    "Phuket, Thailand": {"type": "Island"},
    "Yosemite National Park, USA": {"type": "National Park"},
    "Rome, Italy": {"type": "City"},
    "Rio de Janeiro, Brazil": {"type": "Beach"},
    "Los Angeles, USA": {"type": "Metropolis"},
    "Hawaii, USA": {"type": "Island"},
    "Grand Canyon National Park, USA": {"type": "National Park"},
    "Dubai, UAE": {"type": "City"},
    "Cancun, Mexico": {"type": "Beach"},
    "Singapore": {"type": "Metropolis"},
    "Fiji": {"type": "Island"},
    "Rocky Mountain National Park, USA": {"type": "National Park"},
    "Florence, Italy": {"type": "City"},
    "Miami, USA": {"type": "Beach"},
    "Shanghai, China": {"type": "Metropolis"},
    "Seychelles": {"type": "Island"},
    "Zion National Park, USA": {"type": "National Park"},
    "Barcelona, Spain": {"type": "City"},
    "Maui, USA": {"type": "Beach"},
    "Seoul, South Korea": {"type": "Metropolis"},
    "Crete, Greece": {"type": "Island"},
    "Glacier National Park, USA": {"type": "National Park"},
    "Amsterdam, Netherlands": {"type": "City"},
    "Cabo San Lucas, Mexico": {"type": "Beach"},
    "Moscow, Russia": {"type": "Metropolis"},
    "Santorini, Greece": {"type": "Island"},
    "Denali National Park, USA": {"type": "National Park"},
    "Prague, Czech Republic": {"type": "City"},
    "Mykonos, Greece": {"type": "Beach"},
    "Toronto, Canada": {"type": "Metropolis"},
    "Ibiza, Spain": {"type": "Island"},
    "Great Smoky Mountains National Park, USA": {"type": "National Park"},
    "Venice, Italy": {"type": "City"},
    "Cape Town, South Africa": {"type": "Beach"},
    "Las Vegas, USA": {"type": "Metropolis"},
    "Mauritius": {"type": "Island"},
    "Kruger National Park, South Africa": {"type": "National Park"},
    "Edinburgh, Scotland": {"type": "City"},
    "Nice, France": {"type": "Beach"},
    "Chicago, USA": {"type": "Metropolis"},
    "Skiathos, Greece": {"type": "Island"},
    "Banff National Park, Canada": {"type": "National Park"},
    "Vienna, Austria": {"type": "City"},
    "Gold Coast, Australia": {"type": "Beach"},
    "San Francisco, USA": {"type": "Metropolis"},
    "Palawan, Philippines": {"type": "Island"},
    "Grand Teton National Park, USA": {"type": "National Park"},
    "Berlin, Germany": {"type": "City"},
    "Cape Cod, USA": {"type": "Beach"},
    "New Orleans, USA": {"type": "Metropolis"},
    "Bora Bora, French Polynesia": {"type": "Island"},
    "Rocky Mountain National Park, USA": {"type": "National Park"},
    "Barcelona, Spain": {"type": "City"},
    "Tulum, Mexico": {"type": "Beach"},
    "Dublin, Ireland": {"type": "Metropolis"},
    "Maldives": {"type": "Island"},
    "Everglades National Park, USA": {"type": "National Park"},
    "Copenhagen, Denmark": {"type": "City"},
    "Amalfi Coast, Italy": {"type": "Beach"},
    "Washington D.C., USA": {"type": "Metropolis"},
    "Bora Bora, French Polynesia": {"type": "Island"},
    "Arches National Park, USA": {"type": "National Park"},
    "Budapest, Hungary": {"type": "City"},
    "Mauritius": {"type": "Beach"},
    "Dublin, Ireland": {"type": "Metropolis"},
    "Bora Bora, French Polynesia": {"type": "Island"},
    "Yosemite National Park, USA": {"type": "National Park"}
    }
}

# Function to recommend items based on user preferences
def recommend_items(category, preferences):
    recommended_items = []
    for item, details in data.get(category, {}).items():
        if category != "travel_places" and (details.get("genre") in preferences or details.get("director") in preferences or item in preferences):
            recommended_items.append(item)
        elif category == "travel_places" and (details.get("type") in preferences or item in preferences):
            recommended_items.append(item)
    return recommended_items

# Function to prompt the user to choose a category
def choose_category():
    print("Welcome to the Recommendation System!")
    print("Please choose a category:")
    print("1. Books")
    print("2. Songs")
    print("3. Movies")
    print("4. Travel Places")
    choice = input("Enter your choice (1-4): ")
    categories = {"1": "books", "2": "songs", "3": "movies", "4": "travel_places"}
    return categories.get(choice)

# Example usage
def main():
    category = choose_category()
    if not category:
        print("Invalid choice. Exiting.")
        return

    print("Please enter your preferences. You can enter genres, directors, artists, or specific titles.")
    preferences = input("Enter your preferences (separated by commas): ").split(",")
    recommended_items = recommend_items(category, preferences)
    if recommended_items:
        print("\nRecommended items based on your preferences:")
        for item in recommended_items:
            print(item)
    else:
        print("Sorry, no items match your preferences.")

if __name__ == "__main__":
    main()
